In [86]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

In [87]:
df = pd.read_csv('single_family_home_values.csv')

In [88]:
df.head(2)

id            address    city state  zipcode  latitude   longitude  \
0   39525749    8171 E 84th Ave  Denver    CO    80022  39.84916 -104.893468   
1  184578398  10556 Wheeling St  Denver    CO    80022  39.88802 -104.830930   

   bedrooms  bathrooms  rooms  squareFootage  lotSize  yearBuilt lastSaleDate  \
0         3        2.0      6           1378     9968     2003.0   2009-12-17   
1         2        2.0      6           1653     6970     2004.0   2004-09-23   

   lastSaleAmount priorSaleDate  priorSaleAmount  estimated_value  
0           75000    2004-05-13         165700.0           239753  
1          216935           NaN              NaN           343963

In [89]:
df.shape

(15000, 18)

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   id               15000 non-null  int64  
 1   address          15000 non-null  object 
 2   city             15000 non-null  object 
 3   state            15000 non-null  object 
 4   zipcode          15000 non-null  int64  
 5   latitude         14985 non-null  float64
 6   longitude        14985 non-null  float64
 7   bedrooms         15000 non-null  int64  
 8   bathrooms        15000 non-null  float64
 9   rooms            15000 non-null  int64  
 10  squareFootage    15000 non-null  int64  
 11  lotSize          15000 non-null  int64  
 12  yearBuilt        14999 non-null  float64
 13  lastSaleDate     15000 non-null  object 
 14  lastSaleAmount   15000 non-null  int64  
 15  priorSaleDate    11173 non-null  object 
 16  priorSaleAmount  11287 non-null  float64
 17  estimated_va

In [91]:
df.describe()

id       zipcode      latitude     longitude      bedrooms  \
count  1.500000e+04  15000.000000  14985.000000  14985.000000  15000.000000   
mean   5.176229e+07  80204.919467     39.740538   -104.964076      2.708400   
std    6.190876e+07      9.715263      0.023555      0.039788      0.897231   
min    1.433670e+05  80022.000000     39.614531   -105.108440      0.000000   
25%    1.004802e+07  80205.000000     39.727634   -104.978737      2.000000   
50%    2.563241e+07  80206.000000     39.748048   -104.957689      3.000000   
75%    5.114222e+07  80207.000000     39.758214   -104.937522      3.000000   
max    3.209481e+08  80209.000000     39.888020   -104.830930     15.000000   

          bathrooms         rooms  squareFootage       lotSize     yearBuilt  \
count  15000.000000  15000.000000   15000.000000   15000.00000  14999.000000   
mean       2.195067      6.164133    1514.504400    5820.76620   1929.517168   
std        1.166279      1.958601     830.635999    3013.27947     29.937051   
min        0.000000      0.000000     350.000000     278.00000   1874.000000   
25%        1.000000      5.000000     986.000000    4620.00000   1907.000000   
50%        2.000000      6.000000    1267.500000    5950.00000   1925.000000   
75%        3.000000      7.000000    1766.250000    6270.00000   1949.000000   
max       12.000000     39.000000   10907.000000  122839.00000   2016.000000   

       lastSaleAmount  priorSaleAmount  estimated_value  
count    1.500000e+04     1.128700e+04     1.500000e+04  
mean     4.053563e+05     2.594350e+05     6.371625e+05  
std      7.756998e+05     3.379387e+05     5.044185e+05  
min      2.590000e+02     0.000000e+00     1.477670e+05  
25%      1.940000e+05     1.100000e+05     3.984348e+05  
50%      3.200000e+05     2.100000e+05     5.183575e+05  
75%      4.632000e+05     3.302400e+05     6.879692e+05  
max      4.560000e+07     1.600000e+07     1.014531e+07

In [92]:
X = df.drop('estimated_value', axis=1)

In [93]:
X = X[['bedrooms', 'bathrooms', 'rooms', 'squareFootage', 'lotSize', 'yearBuilt','priorSaleAmount']]

In [94]:
X.fillna(0, inplace=True)

In [95]:
from sklearn.cluster import KMeans

In [96]:
kmean = KMeans(n_clusters=5, random_state=0).fit(X)

In [97]:
kmean

KMeans(n_clusters=5, random_state=0)

In [98]:
kmean.labels_


array([1, 1, 1, ..., 4, 0, 4])

In [99]:
kmean.cluster_centers_

array([[2.70429043e+00, 2.27970297e+00, 6.21221122e+00, 1.47961931e+03,
        5.39453399e+03, 1.92549059e+03, 2.95099200e+05],
       [2.64029666e+00, 1.93461063e+00, 5.86143387e+00, 1.39218925e+03,
        5.94385612e+03, 1.93061051e+03, 3.97987770e+04],
       [3.73118280e+00, 5.64516129e+00, 1.04408602e+01, 4.51996774e+03,
        1.30122688e+04, 1.96766667e+03, 2.37729552e+06],
       [3.00000000e+00, 4.50000000e+00, 9.00000000e+00, 3.74800000e+03,
        8.59750000e+03, 1.99800000e+03, 1.37500550e+07],
       [3.34437086e+00, 3.87549669e+00, 8.48741722e+00, 2.72901854e+03,
        7.02978146e+03, 1.94268477e+03, 7.54147234e+05]])

In [100]:
labels = kmean.labels_

In [101]:
X['cluster'] = labels

In [102]:
X.groupby('cluster').mean()

bedrooms  bathrooms      rooms  squareFootage       lotSize  \
cluster                                                                
0        2.703814   2.276540   6.207033    1476.909031   5394.763579   
1        2.640391   1.934909   5.861775    1392.549189   5943.948274   
2        3.731183   5.645161  10.440860    4519.967742  13012.268817   
3        3.000000   4.500000   9.000000    3748.000000   8597.500000   
4        3.336375   3.868318   8.485007    2726.056063   7007.859192   

           yearBuilt  priorSaleAmount  
cluster                                
0        1925.500578     2.944543e+05  
1        1930.605247     3.965644e+04  
2        1967.666667     2.377296e+06  
3        1998.000000     1.375006e+07  
4        1942.452412     7.505620e+05

In [103]:
X = X.drop('cluster', axis=1)

In [104]:
from sklearn.metrics import silhouette_score

In [105]:
for i in range(3,10):
    kmeans = KMeans(n_clusters=i).fit(X)
   
   
   # print(kmeans.labels_)
    print(silhouette_score(X, kmeans.labels_))
    #print(kmeans.cluster_centers_)


0.6144153008072338
0.616941515911268
0.6327075515456735
0.6463039769369211
0.6518660782558499
0.660940918441709
0.6595577856028569


In [106]:
from sklearn.linear_model import LinearRegression , LogisticRegression
from sklearn.svm import SVR, SVC
from sklearn.neighbors import KNeighborsClassifier , KNeighborsRegressor

In [107]:
X.head(2)

bedrooms  bathrooms  rooms  squareFootage  lotSize  yearBuilt  \
0         3        2.0      6           1378     9968     2003.0   
1         2        2.0      6           1653     6970     2004.0   

   priorSaleAmount  
0         165700.0  
1              0.0

In [108]:
y = df['estimated_value']

In [109]:
lg = LinearRegression()
lg.fit(X, y) #training
lg.score(X, y)

0.7648477834199695

In [110]:
from sklearn.model_selection import train_test_split

In [111]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [112]:
x_train.shape, x_test.shape

((12000, 7), (3000, 7))

In [113]:
lr = LinearRegression()
lr.fit(x_train, y_train)#training
lr.score(x_test, y_test)#testing

0.7563614540707968

In [114]:
df['estimated_value_bins'] = df['estimated_value'].apply(lambda x: 'high' if x < 500000 else 'low')

In [115]:
df.estimated_value_bins.value_counts()

estimated_value_bins
low     7963
high    7037
Name: count, dtype: int64

In [116]:
df.head(2)

id            address    city state  zipcode  latitude   longitude  \
0   39525749    8171 E 84th Ave  Denver    CO    80022  39.84916 -104.893468   
1  184578398  10556 Wheeling St  Denver    CO    80022  39.88802 -104.830930   

   bedrooms  bathrooms  rooms  squareFootage  lotSize  yearBuilt lastSaleDate  \
0         3        2.0      6           1378     9968     2003.0   2009-12-17   
1         2        2.0      6           1653     6970     2004.0   2004-09-23   

   lastSaleAmount priorSaleDate  priorSaleAmount  estimated_value  \
0           75000    2004-05-13         165700.0           239753   
1          216935           NaN              NaN           343963   

  estimated_value_bins  
0                 high  
1                 high

In [117]:
y2 =  df['estimated_value_bins']

In [118]:
log  = LogisticRegression()
X_train, X_test, y2_train, y2_test = train_test_split(X, y2, test_size=0.2, random_state=0)
log.fit(X_train, y2_train)

C:\Users\Acer Nitro 5\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [119]:
log.score(X_test, y2_test)

0.849

In [120]:
log.predict(X_test) , y2_test

(array(['low', 'low', 'low', ..., 'high', 'high', 'low'], dtype=object),
 1670      low
 13379     low
 10234     low
 4719     high
 7003      low
          ... 
 10346    high
 8469      low
 12765    high
 9431     high
 4202     high
 Name: estimated_value_bins, Length: 3000, dtype: object)

In [121]:
np.array(y2_test)

array(['low', 'low', 'low', ..., 'high', 'high', 'high'], dtype=object)

In [122]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y2_test, log.predict(X_test))

array([[1214,  205],
       [ 248, 1333]], dtype=int64)

In [123]:
from IPython.display import Image

In [124]:
scr = SVR()

In [125]:
scr.fit(X_train, y_train)

SVR()

In [126]:
scr.score(X_test, y_test) #malo

-0.0538417774302391

In [127]:
svc = SVC()

In [128]:
svc.fit(X_train, y2_train)
svc.score(X_test, y2_test)

0.7223333333333334

In [129]:
y2_predict = svc.predict(X_test)

In [130]:
confusion_matrix(y2_test, y2_predict)

array([[1301,  118],
       [ 715,  866]], dtype=int64)

In [132]:
##KNN
